// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Test.sol";
import {ProtectedLendingTrustless, IL1Block}
    from "../src/ProtectedLending_Trustless.sol";

/**
 * @title TrustlessRescueTest
 * @notice Tests for trustless (L1-proof) rescue activation.
 *
 * Strategy: test verification logic against a REAL synthetic fixture that
 * uses the exact same MPT/RLP encoding as a real L1 block.
 * The fixture was generated by script/gen_fixture.py:
 *   - A single-entry receipt MPT (txIndex=0)
 *   - Receipt contains a TransactionDeposited log (portal=0x4904..., from=victim)
 *   - Fake header where field[5]=receiptsRoot; keccak=l1BlockHash
 * L1Block.hash() is mocked to return l1BlockHash (standard Foundry practice).
 *
 * Paper disclosure: fixture is synthetic (not a real L1 block) but is
 * structurally identical. MPT traversal, RLP parsing, and log matching use
 * real production code paths.
 *
 * Run: forge test --match-contract TrustlessRescue -vvv
 *      (no --fork-url needed: self-contained)
 */
contract TrustlessRescueTest is Test {

    // Base mainnet OptimismPortal
    address constant PORTAL  = 0x49048044D57e1C92A77f79988d21Fa8fAF74E97e;
    address constant L1BLOCK_ADDR = 0x4200000000000000000000000000000000000015;

    ProtectedLendingTrustless def;

    // ── Fixture vars (filled by _loadRealDepositFixture) ─────────────────────
    address victim;
    bytes32 l1BlockHash;
    bytes   l1HeaderRLP;
    uint256 txIndex;
    bytes   receiptRLP;
    bytes[] trieProof;

    function setUp() public {
        def = new ProtectedLendingTrustless(PORTAL);
        _loadRealDepositFixture();
        // Mock L1Block.hash() → l1BlockHash (standard test practice; disclosed)
        vm.mockCall(
            L1BLOCK_ADDR,
            abi.encodeWithSelector(IL1Block.hash.selector),
            abi.encode(l1BlockHash)
        );
    }

    // ── Tests ─────────────────────────────────────────────────────────────────

    /**
     * @notice Core test: trustless proof → protection activated → liquidation blocked.
     */
    function test_TrustlessRescue_Blocks_Liquidation() public {
        console.log("\n=== Trustless Rescue: Blocks Liquidation ===");

        address prover = makeAddr("prover"); // anyone can submit proof
        vm.prank(prover);
        def.proveRescue(victim, l1HeaderRLP, txIndex, receiptRLP, trieProof);

        assertTrue(def.isProtected(victim), "victim must be protected after proof");
        assertGt(def.rescueDeadline(victim), block.timestamp);

        console.log("Proof submitted by prover (not victim - victim is censored).");
        console.log("rescueDeadline set for 12h.");

        // Adversary tries to liquidate - must revert
        vm.expectRevert("rescue active");
        def.liquidationGuard(victim);

        console.log("[PASS] Liquidation blocked during grace period.");
    }

    /**
     * @notice LIVENESS: grace period expires → liquidation allowed.
     */
    function test_Rescue_Expires_Allows_Liquidation() public {
        def.proveRescue(victim, l1HeaderRLP, txIndex, receiptRLP, trieProof);
        assertGt(def.rescueDeadline(victim), block.timestamp);

        vm.warp(block.timestamp + def.GRACE_PERIOD() + 1);

        // Must NOT revert - liquidation is allowed again
        def.liquidationGuard(victim);
        console.log("[PASS] Liquidation allowed after grace period expiry.");
    }

    /**
     * @notice Anti-griefing: invalid proof cannot activate protection.
     *         Cannot be spammed to manufacture grace periods for healthy positions.
     */
    function test_Griefing_Rejected_NoProof() public {
        bytes[] memory emptyProof;
        vm.expectRevert();
        def.proveRescue(victim, l1HeaderRLP, txIndex, hex"", emptyProof);
        assertEq(def.rescueDeadline(victim), 0, "no protection without valid proof");
        console.log("[PASS] Invalid proof rejected - anti-griefing holds.");
    }

    /**
     * @notice Anti-replay: same proof cannot be used twice.
     */
    function test_Replay_Rejected() public {
        def.proveRescue(victim, l1HeaderRLP, txIndex, receiptRLP, trieProof);
        vm.expectRevert("proof already used");
        def.proveRescue(victim, l1HeaderRLP, txIndex, receiptRLP, trieProof);
        console.log("[PASS] Replay rejected.");
    }

    /**
     * @notice Wrong user: receipt with deposit for alice cannot protect bob.
     */
    function test_WrongUser_Rejected() public {
        address bob = makeAddr("bob");
        require(bob != victim, "bob must differ from victim");
        vm.expectRevert("no deposit for user in receipt");
        def.proveRescue(bob, l1HeaderRLP, txIndex, receiptRLP, trieProof);
        assertEq(def.rescueDeadline(bob), 0);
        console.log("[PASS] Deposit for alice cannot protect bob.");
    }

    /**
     * @notice Gas overhead measurement.
     */
    function test_GasOverhead() public {
        uint256 g0 = gasleft();
        def.proveRescue(victim, l1HeaderRLP, txIndex, receiptRLP, trieProof);
        uint256 proveGas = g0 - gasleft();

        uint256 g1 = gasleft();
        def.liquidationGuard(makeAddr("other")); // healthy user, 1 SLOAD
        uint256 guardGas = g1 - gasleft();

        console.log("proveRescue gas:    ", proveGas);
        console.log("liquidationGuard gas:", guardGas);
    }

    // ── Fixture ───────────────────────────────────────────────────────────────
    // Auto-generated by script/gen_fixture.py
    // Receipt contains: TransactionDeposited(from=0xDeaD..., to=0xDeaD..., version=0)
    // emitted by 0x49048044D57e1C92A77f79988d21Fa8fAF74E97e (Base OptimismPortal on L1)

    function _loadRealDepositFixture() internal {
        victim       = address(0xdeaDDeADDEaDdeaDdEAddEADDEAdDeadDEADDEaD);
        l1BlockHash  = bytes32(hex"3f02ccefb4ac3afdbf22f5169f038c18826c3e2434a3cb019c790b51567c36d2");
        l1HeaderRLP  = hex"f9021da00000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000000940000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000000a0a93814eb7260ea07be6277fb4331c9bccdbcbad6366e06ff63069108913d5437b901000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080018401c9c38083005208846553f10080a000000000000000000000000000000000000000000000000000000000000000008800000000000000008307d000a00000000000000000000000000000000000000000000000000000000000000000";
        txIndex      = 0;
        receiptRLP   = hex"02f901c701825208b9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f8bef8bc9449048044d57e1c92a77f79988d21fa8faf74e97ef884a0b3813568d9991fc951961fcb4c784893574240a28925604d09fc577c55bb7c32a0000000000000000000000000deaddeaddeaddeaddeaddeaddeaddeaddeaddeada0000000000000000000000000deaddeaddeaddeaddeaddeaddeaddeaddeaddeada00000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000000";
        trieProof    = new bytes[](1);
        trieProof[0] = hex"f901d1822080b901cb02f901c701825208b9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f8bef8bc9449048044d57e1c92a77f79988d21fa8faf74e97ef884a0b3813568d9991fc951961fcb4c784893574240a28925604d09fc577c55bb7c32a0000000000000000000000000deaddeaddeaddeaddeaddeaddeaddeaddeaddeada0000000000000000000000000deaddeaddeaddeaddeaddeaddeaddeaddeaddeada00000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000000";
    }
}
